// Author: Rogelio Morrell , 2009
// Name: OsoFramework
// From: Panama
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;


namespace OsoFramework
{


	public interface IDataRepository
	{
        void LoadRepository(string connectionString);
        string ConnectionString { get; set; }
        IEnumerable<T> FindBy<T>(object id) where T : class, IParseData, new();
        IEnumerable<T> FindAll<T>() where T : class, new();
		void Update<T>(T data) where T : class, new();
		void Delete<T>(T data) where T : class, new();
		void Insert<T>(T data) where T : class, new() ;
	}
}
