// Author: Rogelio Morrell , 2009
// Name: OsoFramework
// From: Panama
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Configuration;
using System.Xml.Linq;
using OsoFramework;
using OsoFramework.Http;
using SubSonic;
using OsoExamples.DatabaseSchema;

namespace OsoExamples.Robot
{
    public class GoogleExample : WebRobotBase, IWebRobot
    {
        public void Start()
        {
            Main();
        }

        private void Main()
        {
            // using read
            string goog1 = Read(new HttpSettings { Query = "http://www.google.com" });
            Info(goog1);
            // using get XDocument for url
            // pre parsing is for manually parsing non conforming XHTML
            var goog2 = ReadXml(new HttpSettings { Query = "http://www.google.com" }, x => x);

            byte[] a = ReadWebBinaryResource("http://subsonicproject.com/content/images/SubSonicSMall.png");
            Info("google ended");

        }
   }

    }


