// Author: Rogelio Morrell , 2009
// Name: OsoFramework
// From: Panama
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using OsoFramework;
using SubSonic;
using SubSonic.Repository;
using System.Data.SQLite;
using System.Collections.Generic;

namespace OsoExamples.DatabaseSchema
{


    public class RealEstateDataRepository : DataRepositoryBase // IDataRepositoryBase if custom data access
	{

        public RealEstateDataRepository()
        {
        }
    }
}
