// Author: Rogelio Morrell , 2009
// Name: OsoFramework
// From: Panama
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace OsoFramework.Http
{

public class HTML
    {
        public const string BR = "BR";
        public const string P = "P";
        public const string IMG = "IMG";
        public const string OPTION = "OPTION";
        public const string SELECT = "SELECT";
        public const string INPUT = "INPUT";
        public const string FORM = "FORM";
        public const string SPAN = "SPAN";
        public const string B = "B";
        public const string A = "A";
        public const string PRE = "PRE";
        public const string TR = "TR";
        public const string TD = "TD";
        public const string TABLE = "TABLE";
        public const string TBODY = "TBODY";
        public const string THEAD = "THEAD";
        public const string DIV = "DIV";
    }
}
