//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Author: Rogelio Morrell , 2009
// Name: OsoFramework
// From: Panama


using NUnit.Framework;
using System;
//using WatiN.Core;
//using WatiN.Core.Interfaces;


namespace OsoFramework.Tests
{


	[TestFixture()]
	public class Test
	{


		[Test()]
		public void TestGoogle ()
		{
//				IBrowser firefox = BrowserFactory.Create(BrowserType.FireFox);
//				firefox.GoTo("http://www.google.com");
//				firefox.TextField(Find.ByName("q")).Value = "WatiN";
//				firefox.Button(Find.ByName("btnG")).Click();
//				Assert.IsTrue(firefox.ContainsText("WatiN"));
		}
	}
}
